# Develop: config.yaml

LLM:
  GROQ:
    MODEL: "meta-llama/llama-4-scout-17b-16e-instruct"
    RATE_LIMIT: 0.3   # seconds between request
    MAX_OUTPUT_TOKENS: 1024
    TEMPERATURE: 1

  GEMINI:
    MODEL: "gemini-1.5-flash"
    RATE_LIMIT: 0.3   # seconds between request
    MAX_OUTPUT_TOKENS: 1024
    TEMPERATURE: 1

EMBEDDING:
  NAME: "sentence-transformers/all-MiniLM-L6-v2" # Info: https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2
  # Dimension is required for Milvus
  DIMENSIONS: 384 

DATABASE:
  SQL:
    PATH: "data/document_store/documents.db" 
  MILVUS:
    HOST: "localhost"
    PORT: "19530"
    COLLECTION_NAME: "md_chunks_v1" # Name for the collection in Milvus

DOCUMENT_PROCESSING:
  KNOWLEDGE_BASE_PATH: "data/knowledge_base"
  SUPPORTED_EXTENSIONS: [".pdf", ".md", ".markdown"]

RERANKING:
  ENABLED: true
  PRIMARY_PROVIDER: "jina"
  FALLBACK_ENABLED: true
  
  JINA:
    MODEL_NAME: "jina-reranker-v2-base-multilingual"
    API_BASE: "https://api.jina.ai/v1/rerank"
    MAX_RETRIES: 3
    TIMEOUT: 30
  
  PARAMETERS:
    INITIAL_K: 20  # More candidates for reranking
    FINAL_K: 5     # Final result after reranking
    MIN_SCORE_THRESHOLD: 0.1  # Minimum score to include


